context:
  version: 2.12.5


package:
  name: libxml2
  version: ${{ version }}

source:
  url: https://gitlab.gnome.org/GNOME/libxml2/-/archive/v${{ version }}/libxml2-v${{
    version }}.tar.gz
  sha256: 90f1b12db4b9f9b7282edf33ff15a104bb9caf88264fda05af4239330437e239


build:
  number: 0

requirements:
  build:
  - ${{ compiler("c") }}
  - libtool
  - autoconf
  - automake
  - libtool
  - pkg-config
  run:
  - zlib
  - libiconv
